stages:
  - build
  - test
  - cache
  - analyze 
  - plot

#image used to compile and run code
variables:
  singularity_image: /bigdata/shared/Software/singularity/gpuservers/singularity/images/cupy.simg

libhmm:
  stage: build
  script:
    - git submodule init
    - git submodule update
    - cd tests/hmm
    - singularity exec ${singularity_image} make libhmm.so 
  artifacts:
    paths:
    - tests/hmm/libhmm.so

test-libhmm:
  stage: test
  script:
    - PYTHONPATH=hepaccelerate:. singularity exec ${singularity_image} python3 tests/hmm/test_libhmm.py

run-cache:
  stage: cache
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /ci-rerun-cache/
  script:
    - rm -Rf /nvme1/jpata/gitlab-ci-cache/
    - PYTHONPATH=hepaccelerate:. singularity exec --nv -B /nvme1 -B /nvme2 -B /cvmfs -B /mnt/hadoop -B /bigdata -B /storage ${singularity_image} python3 tests/hmm/analysis_hmumu.py --datapath /storage/user/jpata/ -a cache --maxfiles 5 --cache-location /nvme1/jpata/gitlab-ci-cache/ --nthreads 20

run-analyze:
  stage: analyze
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /ci-rerun-full-analysis/
  script:
    - PYTHONPATH=hepaccelerate:. singularity exec --nv -B /nvme1 -B /nvme2 -B /cvmfs -B /mnt/hadoop -B /bigdata -B /storage ${singularity_image} python3 tests/hmm/analysis_hmumu.py --datapath /storage/user/jpata/ -a analyze --maxfiles 5 --cache-location /nvme1/jpata/gitlab-ci-cache/ --nthreads 20
  artifacts:
    paths:
      - out

run-full-analyze:
  stage: analyze
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /ci-rerun-full-analysis/
  script:
    - PYTHONPATH=hepaccelerate:. singularity exec --nv -B /nvme1 -B /nvme2 -B /cvmfs -B /mnt/hadoop -B /bigdata -B /storage ${singularity_image} python3 tests/hmm/analysis_hmumu.py --datapath /storage/user/jpata/ -a analyze --maxfiles -1 --cache-location /nvme2/jpata/mycache_all_presel/ --nthreads 20
  artifacts:
    paths:
      - out

run-plot:
  stage: plot
  script:
    - PYTHONPATH=hepaccelerate:. singularity exec --nv -B /nvme1 -B /nvme2 -B /cvmfs -B /mnt/hadoop -B /bigdata -B /storage ${singularity_image} python3 hepaccelerate/plotting.py
  artifacts:
    paths:
      - out/baseline/*.pdf
